### ISSUE TITLE
Type of license of this repo. 

### ISSUE THREAD

**Issue by anton-b** [gebi/jungerl#2]
Hello what is type of license is on this repo? It is not clear for most of the libraries.

**Comment by gebi** [comment]
The original description of this repo on sourceforge was "The Jungerl is a dense and chaotic Jungle of Erlang code.". I've mirrored it to github because i don't like touching CVS ;).

As for your question, i don't know further than what i initial imported from CVS and needed for some of my projects, most libraries are under the "EPL" (erlang public license) though https://tldrlegal.com/license/erlang-public-license-v1.1-(erlpl-1.1) but that may vary as you mentioned and some of the code it is less clear, though it's possible to find the code elsewhere to check for license.
But most of the code is from an age way befor proper source control and online services, most of the time it involves digging in old mail archives...

As i've stopped using erlang years ago i can not invest much time in this, but if you want to tackle this task i will happily merge your changes.

**Comment by anton-b** [comment]
Thanks for your answer.
